Update robotreviewer_env.yml
The original line (- mkl=2019.0=118) caused this error:

UnsatisfiableError: The following specifications were found to be in conflict:
  - mkl-service==1.1.2=py36h90e4bf4_5 -> mkl[version='>=2018.0.3,<2019.0a0']
  - mkl==2019.0=118
Use "conda info <package>" to see the dependencies for each package.